# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      # pnpm setup
      # refer to https://github.com/pnpm/action-setup
      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm lint
          pnpm format
          pnpm build
      
      - name: deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          VITE_MAPTILER_KEY: ${{secrets.MAPTILER_KEY}}
        run: |
          echo "VITE_MAPTILER_KEY=${VITE_MAPTILER_KEY}" > .env
          npm run build
          git config --global user.name "watergis+githubci"
          git config --global user.email "watergis+githubci@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${NODE_AUTH_TOKEN}@github.com/watergis/viewer.git
          npm run deploy
